MASTER_UI_SCHEMAS = {
    "bill":  [
{
"fieldID": 1,
"fieldName": "Invoice Number",
"key": "invoicenumber",
"value": [],
"fieldType": "text",
"validation": "alphaNumeric",
"validationPattern": r"^\d{4}$",
"validationMessage": "Must be a 4-digit number",
"isMandatory": True,
"isreadonly": False,
"maxlength": 10,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 2,
"fieldName": "Invoice Date",
"key": "invoicedate",
"value": [],
"fieldType": "date",
"validation": "date",
"validationPattern": r"^(\d{4}-\d{2}-\d{2}|\d{2}-\d{2}-\d{4})$",
"validationMessage": "Must be a valid date (yyyy-mm-dd or dd-mm-yyyy)",
"isMandatory": True,
"isreadonly": False,
"maxlength": 10,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 3,
"fieldName": "Customer Company",
"key": "customercompany",
"value": [],
"fieldType": "text",
"validation": "text",
"validationPattern": "",
"validationMessage": "Required",
"isMandatory": True,
"isreadonly": False,
"maxlength": 100,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 4,
"fieldName": "Address",
"key": "address",
"value": [],
"fieldType": "textarea",
"validation": "text",
"validationPattern": "",
"validationMessage": "",
"isMandatory": False,
"isreadonly": False,
"maxlength": 300,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 5,
"fieldName": "State",
"key": "state",
"value": [],
"fieldType": "dropdown",
"validation": "enum",
"validationPattern": "",
"validationMessage": "Must be one of the allowed states",
"isMandatory": True,
"isreadonly": False,
"maxlength": 30,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": ["Karnataka", "Maharashtra", "Delhi"],
"columnName": ""
},
{
"fieldID": 6,
"fieldName": "Invoice Details",
"key": "invoicedetails",
"value": [],
"fieldType": "repeater",
"validation": "objectList",
"validationPattern": "",
"validationMessage": "Each item must have description, quantity, and price",
"isMandatory": False,
"isreadonly": False,
"maxlength": 0,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": "",
"subFields": [
{
"fieldName": "Description",
"key": "description",
"fieldType": "text",
"validation": "text",
"isMandatory": True
},
{
"fieldName": "Quantity",
"key": "quantity",
"fieldType": "number",
"validation": "number",
"isMandatory": True
},
{
"fieldName": "Price",
"key": "price",
"fieldType": "float",
"validation": "float",
"isMandatory": True
}
]
},
{
"fieldID": 7,
"fieldName": "Total",
"key": "total",
"value": [],
"fieldType": "number",
"validation": "float",
"validationPattern": "",
"validationMessage": "",
"isMandatory": False,
"isreadonly": False,
"maxlength": 20,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 8,
"fieldName": "GST",
"key": "gst",
"value": [],
"fieldType": "number",
"validation": "float",
"validationPattern": "",
"validationMessage": "",
"isMandatory": False,
"isreadonly": False,
"maxlength": 20,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
},
{
"fieldID": 9,
"fieldName": "Grand Total",
"key": "grandtotal",
"value": [],
"fieldType": "number",
"validation": "float",
"validationPattern": "",
"validationMessage": "",
"isMandatory": False,
"isreadonly": False,
"maxlength": 20,
"defaultValue": "",
"dependentField": "",
"CustomValidationFunction": "",
"masterCollection": "",
"columnName": ""
}
]
}